[mcp_servers.mongodb]
command = "cmd"
args = ["/c", "npx", "-y", "mongodb-mcp-server@2"]
type = "stdio"

[mcp_servers.mongodb.env]
MDB_MCP_CONNECTION_STRING = "mongodb://root:password@localhost:27017"
MDB_MCP_READ_ONLY = "true"
